### ISSUE TITLE
Duet example typeError

### ISSUE THREAD

**Issue by stevemk14ebr** [interactiveaudiolab/nussl#104]
#### Description
Duet example fails with typeError

#### Steps/Code to Reproduce
Run duet example code on fresh debian system with python 2.7, install nussl with pip

#### Actual Results
  File "localize.py", line 45, in <module>
    main()
  File "localize.py", line 29, in main
    duet.run()
  File "/home/steve/.local/lib/python2.7/site-packages/nussl/Duet.py", line 145, in run
    hist = self.twoDsmooth(hist, np.array([3]))
  File "/home/steve/.local/lib/python2.7/site-packages/nussl/Duet.py", line 293, in twoDsmooth
    Kmat = np.ones((Kernel, Kernel)) / Kernel ** 2
  File "/home/steve/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 192, in ones
    a = empty(shape, dtype, order)
TypeError: only integer scalar arrays can be converted to a scalar index

#### Versions
Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
('Python', '2.7.13 (default, Jan 19 2017, 14:48:08) \n[GCC 6.3.0 20170118]')
('NumPy', '1.13.3')
('SciPy', '1.0.0')
('Scikit-Learn', '0.19.1')
('librosa', '0.5.1')
('nussl', '0.1.3')

**Comment by ethman** [comment]
Hey @stevemk14ebr, thanks for checking out nussl. It looks like you have an old version of `nussl` (0.1.3). Are you able to reproduce this issue with the most recent version (cloning from the `master` or `development` branch here on github)?

**Comment by paolocolourblind** [comment]
Hi,

I am having the same issue now:
>>> duet.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nussl/Duet.py", line 159, in run
    self.smoothed_hist = self.twoDsmooth(self.non_normalized_hist, np.array([3]))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nussl/Duet.py", line 310, in twoDsmooth
    Kmat = np.ones((Kernel, Kernel)) / Kernel ** 2
  File "/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 223, in ones
    a = empty(shape, dtype, order)
TypeError: only integer scalar arrays can be converted to a scalar index

>>> nussl.version
'0.1.5a10'

**Comment by pseeth** [comment]
DUET is now properly tested to make sure it works end-to-end. Re-open if this is still an issue after you upgrade nussl!
