### ISSUE TITLE
NMF_MFCC; ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by vedvasu** [interactiveaudiolab/nussl#128]
#### Description

- I wanted to apply source separation recursively over separated sources. Example; NFM_MFCC((NFM_MFCC(original_audio)[0]))[0] ..... for n iteration till signal intensity or amplitude reduces to zero.
- NMF_MFCC worked well for the first time but when I provided one of the separated sources again to the algorithm, there was value error (`ValueError: Input contains NaN, infinity or a value too large for dtype('float64')`)

#### Steps/Code to Reproduce

```
def nmf_mfcc(input_file_path):
    signal = nussl.AudioSignal(path_to_input_file=input_file_path)
    nmf_mfcc = nussl.NMF_MFCC(signal, num_sources=2, to_mono=True)
    nmf_mfcc.run()
    sources = nmf_mfcc.make_audio_signals()
    for i, source in enumerate(sources):
        output_file_name = str(i) + '.wav'
        source.write_audio_to_file(output_file_name)

input_file_path = '<DIR_HOME>/original_file.wav'
nmf_mfcc(input_file_path)
input_file_path = '0.wav'
nmf_mfcc(input_file_path)
```

#### Expected Results

- No error is thrown. We should get two signals separated in the second iteration too.
- If the further separation of sources is not possible, we should get one source as signal and other source as silence.

#### Actual Results

- Value error thrown
```
/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py:244: RuntimeWarning: invalid value encountered in double_scalars
  result /= temp_transpose_act[indices]
Traceback (most recent call last):
  File "ss.py", line 84, in <module>
    nmf_mfcc()
  File "ss.py", line 22, in nmf_mfcc
    nmf_mfcc.run()
  File "/usr/local/lib/python2.7/dist-packages/nussl/separation/nmf_mfcc.py", line 192, in run
    self.clusterer.fit_transform(cluster_templates.T)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 909, in fit_transform
    X = self._check_fit_data(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 854, in _check_fit_data
    X = check_array(X, accept_sparse='csr', dtype=[np.float64, np.float32])
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

#### Versions

Linux-4.15.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
('Python', '2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]')
('NumPy', '1.13.1')
('SciPy', '0.19.1')
('Scikit-Learn', '0.18.2')
('librosa', '0.6.2')
('nussl', '0.1.6')

**Comment by ethman** [comment]
Hmmm... interesting. My hunch would be that the first pass is outputting silence in `0.wav`. Would you mind posting the first input audio file? 

Also, is `input_file_path` pointing to a `.csv` file? That shouldn't work. That might be the root of the problem.

**Comment by vedvasu** [comment]
@ethman Here is the gdrive [link](https://drive.google.com/drive/folders/1JO6A4R2OzOIaKqw4LthqBDvlOK3UAzy0?usp=sharing) to the folder with the original recording and two sources obtained after first iterations.
- The first pass is not silence and I have observed that this error occurs for few original recordings as well and all the recordings obtained after first pass (sources after the first iteration).
- Also, `input_file_path` is not a `.csv` (written by mistake in the comment). This is `input_file_path.wav` and I have made the correction in the original comment. Thanks!

I think, there is some problem in `transformers` because (maybe something to do with `reconstruction`) -
- The warning is reflecting the same
- Also, I have observed the same error for other separation algorithms even for the first pass. That means maybe the problem is at some common place.
- If we break the process (keyboard interrupt) due to the longer runtime for such cases, I get the following traceback which means the process is somewhere stuck at transformers.
```
/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py:244: RuntimeWarning: invalid value encountered in double_scalars
  result /= temp_transpose_act[indices]
^CTraceback (most recent call last):
  File "ica.py", line 84, in <module>
    nmf_mfcc()
  File "ica.py", line 22, in nmf_mfcc
    nmf_mfcc.run()
  File "/usr/local/lib/python2.7/dist-packages/nussl/separation/nmf_mfcc.py", line 187, in run
    channel_activation_matrix, channel_templates_matrix = nmf.transform()
  File "/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py", line 200, in transform
    current_distance = self.distance
  File "/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py", line 137, in distance
    return self._euclidean_distance() if self._do_euclidean else self._kl_divergence()
  File "/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py", line 322, in _euclidean_distance
    return sum((self.input_matrix[index] - val) ** 2 for index, val in np.ndenumerate(self.reconstructed_matrix))
  File "/usr/local/lib/python2.7/dist-packages/nussl/transformers/transformer_nmf.py", line 322, in <genexpr>
    return sum((self.input_matrix[index] - val) ** 2 for index, val in np.ndenumerate(self.reconstructed_matrix))
KeyboardInterrupt
```

**Comment by tiogoGit** [comment]
I met the same problem when trying to run a decomp......
`C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py:244: RuntimeWarning: invalid value encountered in double_scalars
  result /= temp_transpose_act[indices]
C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py:322: RuntimeWarning: invalid value encountered in double_scalars
  return sum((self.input_matrix[index] - val) ** 2 for index, val in np.ndenumerate(self.reconstructed_matrix))
^CTraceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:/OTS-by-ZS-and-KYF/dataHelper/Audio.py", line 44, in <module>
    main()
  File "D:/OTS-by-ZS-and-KYF/dataHelper/Audio.py", line 30, in main
    m = audio_decomp(audio=audio, OutputPath=OutputPath, file=name)
  File "D:/OTS-by-ZS-and-KYF/dataHelper/Audio.py", line 11, in audio_decomp
    nmf_mfcc.run()
  File "C:\Users\Administrator\Mugi\lib\site-packages\nussl\separation\nmf_mfcc.py", line 187, in run
    channel_activation_matrix, channel_templates_matrix = nmf.transform()
  File "C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py", line 200, in transform
    current_distance = self.distance
  File "C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py", line 137, in distance
    return self._euclidean_distance() if self._do_euclidean else self._kl_divergence()
  File "C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py", line 322, in _euclidean_distance
    return sum((self.input_matrix[index] - val) ** 2 for index, val in np.ndenumerate(self.reconstructed_matrix))
  File "C:\Users\Administrator\Mugi\lib\site-packages\nussl\transformers\transformer_nmf.py", line 322, in <genexpr>
    return sum((self.input_matrix[index] - val) ** 2 for index, val in np.ndenumerate(self.reconstructed_matrix))
KeyboardInterrupt`
@ethman

**Comment by pseeth** [comment]
We moved this implementation to TimbreClustering in the latest version of nussl. It's a bit more stable now and hopefully works better for you!
