### ISSUE TITLE
import nussl error

### ISSUE THREAD

**Issue by monteirojim** [interactiveaudiolab/nussl#154]
#### Description

import nussl produces error - ModuleNotFoundError: No module named 'audio_signal'
#### Steps/Code to Reproduce

>>> import nussl

>>> 

#### Actual Results

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joaquim/anaconda3/envs/audio_test_env/lib/python3.7/site-packages/nussl/__init__.py", line 26, in <module>
    from .core.constants import *
  File "/home/joaquim/anaconda3/envs/audio_test_env/lib/python3.7/site-packages/nussl/core/__init__.py", line 7, in <module>
    from audio_signal import AudioSignal
ModuleNotFoundError: No module named 'audio_signal'
#### Versions

>>> import platform; print(platform.platform())
Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
>>> import sys; print("Python", sys.version)
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.1
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.20.2
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.3
>>> import nussl; print("nussl", nussl.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joaquim/anaconda3/envs/audio_test_env/lib/python3.7/site-packages/nussl/__init__.py", line 26, in <module>
    from .core.constants import *
  File "/home/joaquim/anaconda3/envs/audio_test_env/lib/python3.7/site-packages/nussl/core/__init__.py", line 7, in <module>
    from audio_signal import AudioSignal
ModuleNotFoundError: No module named 'audio_signal'
>>>

**Comment by monteirojim** [comment]
solved by creating an environment with python 2.7 and the following within the env
conda create --name myenv numpy scipy matplotlib python=2.7
(myenv) $ sudo pip install nussl
(myenv) $ pip install musdb
(myenv) $ pip install museval

And for the Spyder IDE for python 2.7
(myenv) $ conda install spyder

**Comment by monteirojim** [comment]
Solved by creating an environment with python 2.7 and the following within the env
conda create --name myenv numpy scipy matplotlib python=2.7
(myenv) $ sudo pip install nussl
(myenv) $ pip install musdb
(myenv) $ pip install museval

And for the Spyder IDE for python 2.7
(myenv) $ conda install spyder
