### ISSUE TITLE
cannot import name 'modules' from 'nussl.deep'

### ISSUE THREAD

**Issue by nathanshelly** [interactiveaudiolab/nussl#157]
Trying to import a version of `nussl` that uses deep learning (specifically the `clustering` branch) results in errors due to unspecified dependencies.

Reproduction:

```bash
> pip install git+https://github.com/interactiveaudiolab/nussl.git@clustering
...
> python -c 'import nussl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/__init__.py", line 27, in <module>
    from .separation import *
  File "/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/separation/__init__.py", line 55, in <module>
    from .clustering import SpatialClustering, PrimitiveClustering
  File "/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/separation/clustering/__init__.py", line 1, in <module>
    from .clustering_algorithms import SpatialClustering, DeepClustering, PrimitiveClustering
  File "/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/separation/clustering/clustering_algorithms.py", line 1, in <module>
    from .clustering_separation_base import ClusteringSeparationBase
  File "/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/separation/clustering/clustering_separation_base.py", line 11, in <module>
    from ...deep import modules
ImportError: cannot import name 'modules' from 'nussl.deep' (/Users/nathanshelly/projects/personal/sandbox/python_dependencies/virtualenv/env/lib/python3.7/site-packages/nussl/deep/__init__.py)
```

This can be solved by also installing `torch` & `zarr` - `pip install torch zarr`.

**Comment by nathanshelly** [comment]
Touches on a similar issue to #130. Potentially an opportunity to revisit that question.

**Comment by pseeth** [comment]
Fixed in the latest refactor.
