### ISSUE TITLE
Import fails when nussl is imported from a relative local path 

### ISSUE THREAD

**Issue by nkundiushuti** [interactiveaudiolab/nussl#89]
I haven't installed nussl, but I tried to import it from the same directory (I copied demo_nmf3.py to the parent directory). I have all the dependencies installed.
Edit: the problem appears even if nussl is installed as a package. 
Traceback (most recent call last):
  File "demo_nmf3.py", line 6, in <module>
    import nussl
  File "/Volumes/Macintosh HD 2/Documents/git/nussl/nussl/__init__.py", line 6, in <module>
    from nussl.utils import *
  File "/Volumes/Macintosh HD 2/Documents/git/nussl/nussl/utils.py", line 14, in <module>
    from audio_signal import AudioSignal
  File "/Volumes/Macintosh HD 2/Documents/git/nussl/nussl/audio_signal.py", line 15, in <module>
    import nussl.separation.masks.mask_base
  File "/Volumes/Macintosh HD 2/Documents/git/nussl/nussl/separation/__init__.py", line 10, in <module>
    from KAM import kam
  File "/Volumes/Macintosh HD 2/Documents/git/nussl/nussl/separation/KAM.py", line 29, in <module>
    from nussl.audio_signal import AudioSignal
ImportError: cannot import name AudioSignal

**Comment by nkundiushuti** [comment]
mostly this: https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x#9252628
I can do a pull request and fix it

**Comment by ethman** [comment]
This has been fixed in the `fixing_imports` branch and will be propagated to the other branches shortly.
